# Generated by Django 3.1.7 on 2021-04-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register_user',
            options={'verbose_name_plural': 'Register_user'},
        ),
    ]
