# Generated by Django 3.1.7 on 2021-04-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagement', '0004_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currency'},
        ),
    ]
