# Generated by Django 3.1.7 on 2021-04-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password1', models.CharField(max_length=120)),
                ('password2', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Register',
            },
        ),
    ]
