# Generated by Django 3.1.7 on 2021-04-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagement', '0002_auto_20210403_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register_user',
            new_name='Register',
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name_plural': 'Register'},
        ),
    ]
